[versions]
kotlin = "2.1.21"
ktx-serialization = "1.9.0"
jda = "6.0.0-preview_DEV"
jda-ktx = "0.12.0"
caffeine = "3.2.2"
harmonylogging = "1.0.2"
logback = "1.5.18"
guava = "32.1.3-jre"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
jda-ktx = { module = "club.minnced:jda-ktx", version.ref = "jda-ktx" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
harmony-logging = { module = "net.perfectdreams.harmony.logging:harmonylogging-slf4j", version.ref = "harmonylogging" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
google-guava = { module = "com.google.guava:guava", version.ref = "guava"}

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "ktx-serialization" }